### ISSUE TITLE
修改keylength之后申请证书，总是提示服务器Overload

### ISSUE THREAD

**Issue by torinkan** [stilleshan/rssforever#10]
提示如图，换申请服务器也没用，应该是某个参数不对，我是用acme.sh手动申请可以成功

![image](https://user-images.githubusercontent.com/13595721/229991062-84f3825f-4b6a-469f-bfea-666844acef6d.png)

望解答！谢谢

**Comment by stilleshan** [comment]
let's encrypt 有次数限制，是不是最近频繁申请了？ https://letsencrypt.org/zh-cn/docs/rate-limits/

我刚测试我的脚本没有问题。

![截屏2023-04-05 13 43 26](https://user-images.githubusercontent.com/22582966/229991975-5aec03e5-4b7e-4554-8d1e-1d1621fcac68.jpg)

**Comment by torinkan** [comment]
感谢大佬回复。因为之前申请ECC证书导致脚本走不下去，我4/3号申请了10张，难道已经超过了限制？我可以不指定let's encrypt 使用默认的ZeroSSL吗？

**Comment by stilleshan** [comment]
脚本有个bug,已经修复，你用脚本时选择 zerossl 就可以了
