### ISSUE TITLE
安装Freshrss步骤三选择PostgreSQL, 按照Readme中填写报错Access denied

### ISSUE THREAD

**Issue by torinkan** [stilleshan/rssforever#11]
如图，使用的是最新的FreshRSS 1.21.0，PostgreSQL使用的是默认postgres:12-alpine，需要升级吗？

![image](https://user-images.githubusercontent.com/13595721/230031935-1cf44f92-e32f-417e-afed-38340d0f1417.png)

望解答，谢谢！

**Comment by stilleshan** [comment]
freshrss.db 是 docker compose 的容器名也是地址，你肯定修改了 docker-compose.yml 了，所以这里的地址就不能是这个。

**Comment by torinkan** [comment]
感谢回答和指导，确实是我去年不知道什么原因脑子抽了把它删掉了，自己都忘了
