### ISSUE TITLE
请教关于Ngixn配置

### ISSUE THREAD

**Issue by torinkan** [stilleshan/rssforever#12]
大佬好，我用你的docker compose 配置文件成功搭建了RSS服务器，现在又在这台服务器上用docker又搭了一个网站，想通过修改当前的Nginx配置文件把它加入当前域名下.

由于是一个小白，我就照葫芦画瓢，把vhost下面的rsshub.conf复制并修改以下内容，但是这样导致nginx服务一直重启，所以请大佬指点一下! 谢谢

![image](https://github.com/stilleshan/rssforever/assets/13595721/c9a4d263-bbfd-41f8-9ab0-1b0af4a08a13)

**Comment by stilleshan** [comment]
首先，你是单独用docker启的一个服务网站么？ 如果是的，那么第一个红圈 podcast:8088 就是导致nginx报错的原因。

只有在同一个 docker-compose.yml 内的各个docker容器才能用这种服务名通信，所以你独立的 podcast docker 是无法被nginx访问到的。

你可以改为IP，docker访问宿主机的IP一般是 172.17.0.1,你把这里改为 podcats:8088改为 172.17.0.1:8088

另外第一行 rssforever-rsshub 是唯一的，如果你也用了rsshub，这里也有可能冲突报错，你应该改为其他字段，例如 podcast 即可。

下面有2个 proxy_pass http://podcast; 记得也改掉。在来试试

**Comment by torinkan** [comment]
感谢大佬的帮忙！改完之后可以了 :)
