### ISSUE TITLE
尝试升级freshrss和Postgres，但是Postgres 13.14 一直重启

### ISSUE THREAD

**Issue by torinkan** [stilleshan/rssforever#13]
大佬帮忙看下，谢谢！如果把postgres改成之前的12就没有问题

尝试修改.env进行升级，老的配置如下
# ------------------------------------- FreshRSS ------------------------------------- #
FRESHRSS_X86_VERSION=1.21.0
FRESHRSS_ARM_VERSION=1.19.1-arm
POSTGRES_DB=freshrss
POSTGRES_USER=freshrss
EXPOSED_PORT=30001

更新如下

![image](https://github.com/stilleshan/rssforever/assets/13595721/48a83e1a-2025-4a2d-9516-ff005ae8060c)

其中YML文件也做了相应的更改，然后运行Docker-copose up -d 后其他都运行正常，只有Postgrs一直重启

![image](https://github.com/stilleshan/rssforever/assets/13595721/a040318c-3534-4e54-bb43-83c856b11065)

手动访问fressrss，就如下报错，

HTTP 500: Application problem
Access to database is denied for `freshrss`: SQLSTATE[08006] [7] could not translate host name "freshrss.db" to address: Name or service not known

其中fressrss.db是之前YML配置的名字

![image](https://github.com/stilleshan/rssforever/assets/13595721/34a346ab-3884-4e1c-95b0-3c8b78043779)

**Comment by stilleshan** [comment]
更新改过 freshrss.db， 如果你是老的，就保持以前的名称 freshrss.db，就能连上数据库了

**Comment by torinkan** [comment]
我一开始其实是保持的老的名字，但是不行后面改成db还是不行，我尝试12以后的几个版本的数据库都起不来

**Comment by stilleshan** [comment]
freshrss 尽量不要升级大版本，数据库这块容易有问题。
