### ISSUE TITLE
在Ubuntu18.0.4 lts中部署遇到问题

### ISSUE THREAD

**Issue by SweeTisG00D** [stilleshan/rssforever#5]
您好。我在您的博客中看到了rssforever，抱着学习的态度开始了第一次部署。因为前期准备工作不足，第一次部署没有成功，于是我采用了您博客中的方法删除了/root/rssforever文件夹，顺便删除了/root目录下类似21555之类的文件夹。在我删除文件夹之后，他没会在不到一分钟内自动恢复，查看得知自动恢复的文件夹里只包含rss这个子文件夹。开始我意识到可能是docker的问题，于是我采用dpkg -l | grep --purge docker这个命令查询出了docker的包。采用sudo apt remove --purge删除了所有docker的包。并且删除了docker-compose的二进制文件。为了保险，我选择了重启我的vps，使用rm -rf 删除了/root/rssforever，在没有重新安装docker的情况下，/root目录不会自动生成rssforever文件夹。接着，按照您博客中的方法重新的安装docker docker-compose。在重新安装docker不久之后，/root目录下还是会自动出现rssforever并且只包含rss这个子文件夹。导致新的安装无法进行，还请为我解答，谢谢。

**Comment by stilleshan** [comment]
按你说发重启过服务器,重装过docker,应该不会自动出现rssforever目录.

只有执行install.sh脚本,没有 /root/rssforever ,docker和docker-compose,以及git都安装了..满足这几个条件才会执行.

**Comment by stilleshan** [comment]
Ubuntu18.0.4 lts 我没有测试过,但本脚本应该不会有这方面兼容问题

**Comment by SweeTisG00D** [comment]
已经确定是docker的问题了，尚不了解该问题如何发生。docker启动之后，就会在/root目录下生成rssforver文件夹，其中只包含rss子文件夹，关闭docker服务就不会出现。
