### ISSUE TITLE
【功能建议】增加自定义上传域名证书文件功能

### ISSUE THREAD

**Issue by ghost** [stilleshan/rssforever#6]
如图，看到大佬写的用法中没有自定义域名

但是.env文件配置中有提到上传域名证书后修改证书文件名的配置

<img width="579" alt="image" src="https://user-images.githubusercontent.com/43143519/194896614-e84f8c2a-e7b2-4b45-8150-162ac74e47a0.png">

自己上传并尝试了下并未成功，还请大佬指教

**Comment by stilleshan** [comment]
.env 前几行都是定义域名的

**Comment by ghost** [comment]
我描述得不太清不好意思，不是自定义域名，是自定义域名证书，就是不通过项目来申请证书，而是导入自己申请的证书实现https

**Comment by stilleshan** [comment]
那你可以在脚本里选http模式，回头成功了，在回来修改 env 里的 https 的模式证书等
