### ISSUE TITLE
建议添加非web服务选项

### ISSUE THREAD

**Issue by vitaminx** [stilleshan/rssforever#7]
建议在此脚本基础上添加几条不自动配置Nginx选项
你这个脚本适合全新服务器，但是作为全新服务器又有些依赖需要提前安装
但是一般的vps都已经部署了web服务
所以添加几条纯docker项目一键比较好，比如：

TTRSS + RSSHub + Watchtower + 手动配置web服务
TTRSS + Watchtower + 手动配置web服务
FreshRSS + RSSHub + Watchtower + 手动配置web服务
FreshRSS +  + Watchtower + 手动配置web服务

这样可以不会与vps上现有的服务冲突
既可以简单用caddy2直接反代相关服务端口
也可以用acme.sh申请ssl证书然后Nginx反代

至于说自动检测是否已安装web服务然后自动部署，能最好不能有以上手动也可以用

**Comment by stilleshan** [comment]
早前就想过的,但是会弄反向代理的基本上也不需要我这个服务,都会自己装.

这个项目目的就是为不懂的小白用户一键搞定.
