### ISSUE TITLE
使用脚本证书申请成功，但是脚本判断申请证书失败

### ISSUE THREAD

**Issue by torinkan** [stilleshan/rssforever#8]
Hello 大佬，

我在使用您的脚本部署时，在申请证书阶段一直失败，从返回的日志来看，证书是获取成功的，但是脚本逻辑判断失败，本人不懂脚本，怀疑是脚本路径出现问题：

我脚本返回的结果，路径中域名后面多了“_ecc”

![image](https://user-images.githubusercontent.com/13595721/229358325-3d71b833-97d7-4de7-a834-e5d062e4f5c8.png)

而脚本判断只是域名，我fork了，手动在${DOMAIN}后面添加_ecc, 仍然报错。
f [ ! -f "${WORK_PATH}/${TEMP}/${DOMAIN}/fullchain.cer" ] 

望请解答！谢谢

**Comment by stilleshan** [comment]
acme 启用默认证书味 ecc，我忘记修改了，一会修复。

**Comment by stilleshan** [comment]
https://github.com/stilleshan/rssforever/commit/be3befcd64dbd50d3e052c084ecc2ef8626cab11
